# THE FOLLOWING ACTIONS CODE IS FROM THE PSYCH ENGINE REPO: https://github.com/ShadowMario/FNF-PsychEngine/blob/main/.github/workflows/main.yml
# REMOVED RESERVED COMPILER FLAGS

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          
          :: Forzar Versiones Base Correctas
          haxelib install lime 7.9.0 --always
          haxelib install openfl 9.1.0 --always
          haxelib install flixel 4.11.0 --always
          
          haxelib run lime setup flixel
          haxelib run lime setup
          
          :: Forzar Versiones de Addons y UI Compatibles
          haxelib install flixel-tools --always
          haxelib install flixel-ui 2.4.0 --always
          haxelib set flixel-ui 2.4.0
          haxelib install flixel-addons 2.11.0 --always
          haxelib set flixel-addons 2.11.0
          
          :: Otras dependencias del Mod
          haxelib install tjson --always
          haxelib install hxjsonast --always
          haxelib install hscript --always
          
          :: Repositorios Git con parches específicos de FNF
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit --always
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --always
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --always
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit --always
          haxelib git faxe https://github.com/uhrobots/faxe --always
          haxelib git polymod https://github.com/MasterEric/polymod.git --always
          
          :: Instalar hxCodec estable con VideoHandler
          haxelib install hxCodec 2.6.1 --always
          
          haxelib install hxcpp-debug-server --always
          haxelib list
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
        shell: cmd

      - name: Compile
        run: haxelib run lime build windows -D dcb --app-version="4.0.0-${{ github.run_id}}"
        shell: cmd

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
