name: Compilar Dave and Bambi

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Instalar Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Configurar e Instalar Librerías
        run: |
          haxelib setup .haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run openfl setup
          haxelib install flixel-tools
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit
          haxelib git faxe https://github.com/ashea-code/faxe
          haxelib git polymod https://github.com/MasterSenshi/polymod-fixed
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib list
        shell: cmd

      - name: Compilar Juego (Release)
        run: |
          haxelib run lime build windows -release
        shell: cmd

      - name: Publicar Ejecutable Terminado
        uses: actions/upload-artifact@v4
        with:
          name: Dave-and-Bambi-Windows-Build
          path: export/release/windows/bin/*
